"""Portable, single-column reference layout with original embedded font outlines.

This intentionally supports the ruled, single-column resume family only. It
rejects missing glyphs, overlapping date rows and page overflow; it never fits
content by shrinking fonts. PDF subset cmaps are interpreted through ToUnicode.
"""

from __future__ import annotations

import hashlib
import json
import re
import struct
from collections import Counter
from collections.abc import Mapping
from io import BytesIO
from pathlib import Path
from statistics import median

import pdfplumber
from pdfminer.pdfexceptions import PDFException
from pypdf import PdfReader
from pypdf.errors import PyPdfError
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont, TTFError
from reportlab.pdfgen.canvas import Canvas

from venator.profile.facts import confirmed
from venator.resume.render import (
    sections,
    smarten,
    SUPERSCRIPTS,
    SUPER_SCALE,
    SUPER_RISE,
)


class ReferenceLayoutError(ValueError):
    pass


def _hash(data):
    return hashlib.sha256(data).hexdigest()


def _style(character):
    name = character["fontname"]
    return "bold" if "Bold" in name else "italic" if any(s in name for s in ("Italic", "Oblique")) else "regular"


class ReferenceOverflowError(ReferenceLayoutError):
    """Content cannot fit at the captured font sizes and margins."""


def _font(name, data):
    font = TTFont(name, BytesIO(data))
    # ReportLab's format-6 reader reverses code/glyph fields. Read the actual
    # trimmed cmap when present, so PDFs generated by ReportLab also round-trip.
    table = font.face.get_table("cmap")
    count = struct.unpack_from(">H", table, 2)[0]
    records = [
        struct.unpack_from(">HHI", table, 4 + index * 8) for index in range(count)
    ]
    if any(
        platform in (0, 3) and struct.unpack_from(">H", table, offset)[0] != 6
        for platform, _, offset in records
    ):
        return font
    for _, _, offset in records:
        if struct.unpack_from(">H", table, offset)[0] != 6:
            continue
        first, count = struct.unpack_from(">HH", table, offset + 6)
        glyphs = struct.unpack_from(f">{count}H", table, offset + 10)
        font.face.charToGlyph = {first + i: glyph for i, glyph in enumerate(glyphs)}
        font.face.charWidths = {
            code: font.face.hmetrics[glyph][0] * 1000 / font.face.unitsPerEm
            for code, glyph in font.face.charToGlyph.items()
        }
        break
    return font


def _identity(font):
    table = font.face.get_table("name")
    _, count, offset = struct.unpack(">HHH", table[:6])
    versions = []
    for i in range(count):
        platform, _, _, name_id, length, start = struct.unpack(
            ">HHHHHH", table[6 + 12 * i : 18 + 12 * i]
        )
        if name_id == 5:
            versions.append(
                table[offset + start : offset + start + length].decode(
                    "utf-16-be" if platform == 3 else "latin1"
                )
            )
    return font.face.familyName, font.face.fullName, tuple(sorted(set(versions)))


def capture_reference(
    source_pdf: Path | str,
    directory: Path | str,
    *,
    font_directory: Path | str | None = None,
) -> dict:
    """Capture layout and embedded TTF assets, never modifying the source PDF."""
    source = Path(source_pdf).read_bytes()
    reader = PdfReader(BytesIO(source))
    if len(reader.pages) != 1 or reader.pages[0].get("/Rotate", 0):
        raise ReferenceLayoutError(
            "Reference must be one unrotated, single-column page."
        )
    with pdfplumber.PDF(BytesIO(source)) as document:
        page = document.pages[0]
        lines = page.extract_text_lines()
        chars = page.chars
        used_fonts = {c["fontname"] for c in chars}
        rules = [
            line
            for line in page.lines
            if abs(line["y1"] - line["y0"]) < 0.2
            and line["x1"] - line["x0"] > page.width * 0.75
        ]
        if not chars or len(rules) < 2:
            raise ReferenceLayoutError(
                "Unsupported reference: expected selectable text and full-width section rules."
            )
        body = Counter(round(c["size"], 2) for c in chars).most_common(1)[0][0]
        headers = [
            line
            for line in lines
            if all("Bold" in c["fontname"] and c["size"] > body for c in line["chars"])
        ]
        if len(headers) < 2:
            raise ReferenceLayoutError(
                "Reference needs a name and distinct section headings."
            )
        name = max(headers, key=lambda line: max(c["size"] for c in line["chars"]))
        headers = [line for line in headers if line is not name]
        if not headers:
            raise ReferenceLayoutError(
                "Unsupported reference: no distinct section headings."
            )
        left = median(line["x0"] for line in headers)
        if any(abs(line["x0"] - left) > 2 for line in headers):
            raise ReferenceLayoutError(
                "Multiple-column or inconsistent section headings are unsupported."
            )
        # Long interior whitespace between body chunks is allowed only on a
        # date/title row. Independent prose columns are not a supported layout.
        for line in lines:
            cs = sorted(line["chars"], key=lambda c: c["x0"])
            gaps = [(a, b) for a, b in zip(cs, cs[1:]) if b["x0"] - a["x1"] > 40]
            if (
                gaps
                and line["top"] > headers[0]["top"]
                and not any("Bold" in c["fontname"] for c in cs)
            ):
                raise ReferenceLayoutError("Multiple-column body text is unsupported.")
        body_lines = [
            line for line in lines if abs(line["chars"][0]["size"] - body) < 0.1
        ]
        pitches = [
            b["top"] - a["top"]
            for a, b in zip(body_lines, body_lines[1:])
            if 8 < b["top"] - a["top"] < 14
        ]
        pitch = median(pitches) if pitches else body * 1.1
        bullet_lines = [line for line in lines if line["text"].startswith("•")]
        if not bullet_lines:
            raise ReferenceLayoutError(
                "Reference must include bullets to measure their geometry."
            )
        bullet_text = [
            next(c["x0"] for c in line["chars"][1:] if c["text"].strip())
            for line in bullet_lines
        ]
        contact = next(
            line
            for line in lines
            if line["top"] > name["top"] and line["top"] < headers[0]["top"]
        )
        first = headers[0]
        after = next(line for line in lines if line["top"] > first["top"])
        heading_chars = sorted(after["chars"], key=lambda c: c["x0"])
        for index, (a, b) in enumerate(zip(heading_chars, heading_chars[1:])):
            if b["x0"] - a["x1"] > 40:
                heading_chars = heading_chars[:index + 1]
                break
        location_style = next((_style(c) for c in heading_chars if c["text"] == "-"), "bold")
        before_gaps = [
            h["top"] - max(line["top"] for line in lines if line["top"] < h["top"])
            for h in headers[1:]
        ]
        rule_offset = median(
            min(rules, key=lambda r: abs(r["top"] - h["top"]))["top"] - h["top"]
            for h in headers
        )
        ascent = median(
            (page.height - c["matrix"][5] - c["top"]) / c["size"] for c in chars
        )
        labeled_gaps = []
        for header in headers:
            following = next(line for line in lines if line["top"] > header["top"])
            if ":" in following["text"]:
                labeled_gaps.append(following["top"] - header["top"])
        entry_gaps = []
        for previous, line in zip(lines, lines[1:]):
            cs = sorted(line["chars"], key=lambda c: c["x0"])
            has_date_gap = any(b["x0"] - a["x1"] > 40 for a, b in zip(cs, cs[1:]))
            if (
                previous not in headers
                and has_date_gap
                and any("Bold" in c["fontname"] for c in cs)
            ):
                gap = line["top"] - previous["top"]
                if pitch <= gap < 2 * pitch:
                    entry_gaps.append(gap)

        layout = dict(
            width=page.width,
            height=page.height,
            left=left,
            right=max(c["x1"] for c in chars),
            name_top=name["top"],
            name_x=name["x0"],
            name_align="center" if abs((name["x0"] + name["x1"]) / 2 - page.width / 2) < 2 else "left",
            name_size=name["chars"][0]["size"],
            contact_top=contact["top"],
            contact_size=contact["chars"][0]["size"],
            contact_style=_style(contact["chars"][0]),
            contact_x=contact["x0"],
            contact_align="center" if abs((contact["x0"] + contact["x1"]) / 2 - page.width / 2) < 2 else "left",
            contact_separator=next((separator for separator in (" • ", " | ", " · ") if separator in contact["text"]), " • "),
            education_location_style=location_style,
            first_header_top=first["top"],
            section_size=first["chars"][0]["size"],
            body_size=body,
            pitch=pitch,
            entry_gap=median(entry_gaps) if entry_gaps else pitch,
            section_gap=median(before_gaps),
            header_gap=after["top"] - first["top"],
            labeled_header_gap=median(labeled_gaps)
            if labeled_gaps
            else after["top"] - first["top"],
            rule_offset=rule_offset,
            rule_left=rules[0]["x0"],
            rule_right=rules[0]["x1"],
            rule_width=rules[0]["linewidth"],
            bullet_x=median(l["x0"] for l in bullet_lines),
            bullet_size=median(line["chars"][0]["size"] for line in bullet_lines),
            bullet_text_x=median(bullet_text),
            ascent=ascent,
            bottom=page.height - left,
        )
    assets = {}
    for font_ref in reader.pages[0]["/Resources"]["/Font"].values():
        font = font_ref.get_object()
        name = str(font["/BaseFont"])
        if name.lstrip("/") not in used_fonts:
            continue
        descriptor = font.get("/FontDescriptor")
        face = (
            "bold"
            if "Bold" in name
            else "italic"
            if descriptor and descriptor.get_object().get("/ItalicAngle", 0)
            else "regular"
        )
        if (
            face in assets
            or not descriptor
            or "/FontFile2" not in descriptor.get_object()
            or "/ToUnicode" not in font
        ):
            raise ReferenceLayoutError(
                "Unsupported font configuration: need one embedded TrueType face per style with ToUnicode."
            )
        data = descriptor.get_object()["/FontFile2"].get_data()
        embedded = _font("embedded", data)
        cmap_text = font["/ToUnicode"].get_data().decode("ascii")
        if "beginbfrange" in cmap_text:
            raise ReferenceLayoutError(
                "Unsupported ranged font encoding; supply a reference with a simple Unicode cmap."
            )
        mapping = {}
        for block in re.findall(r"beginbfchar(.*?)endbfchar", cmap_text, re.S):
            for code, value in re.findall(
                r"<([0-9A-Fa-f]+)>\s*<([0-9A-Fa-f]+)>", block
            ):
                character = bytes.fromhex(value).decode("utf-16-be")
                if len(character) != 1:
                    raise ReferenceLayoutError(
                        "Multi-character font glyphs are unsupported."
                    )
                source_code = int(code, 16)
                if ord(character) and embedded.face.charToGlyph.get(source_code):
                    mapping[str(ord(character))] = source_code
        if not mapping:
            raise ReferenceLayoutError("Reference has no usable Unicode font map.")
        if font_directory is not None:
            embedded = _font("embedded", data)
            matched = None
            for candidate in Path(font_directory).glob("*.ttf"):
                full = TTFont("candidate", str(candidate))
                if _identity(full) != _identity(embedded):
                    continue
                if any(
                    abs(
                        full.face.charWidths.get(int(char), -1000)
                        - embedded.face.charWidths[code]
                    )
                    > 0.1
                    for char, code in mapping.items()
                ):
                    continue
                matched = candidate.read_bytes()
                break
            if matched is None:
                raise ReferenceLayoutError(
                    f"No matching full {face} font with identical family, version and glyph widths."
                )
            data = matched
            mapping = None
        assets[face] = (
            data,
            dict(
                file=f"{face}.ttf",
                sha256=_hash(data),
                name=name,
                unicode_to_code=mapping,
            ),
        )
    if set(assets) != {"regular", "bold", "italic"}:
        raise ReferenceLayoutError(
            "Reference needs embedded regular, bold and italic fonts."
        )
    metadata = dict(
        version=1,
        source_sha256=_hash(source),
        layout=layout,
        fonts={face: asset[1] for face, asset in assets.items()},
    )
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    for data, asset in assets.values():
        (target / asset["file"]).write_bytes(data)
    (target / "layout.json").write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8", newline="\n")
    return metadata


def _load(directory):
    try:
        status_path = Path(directory) / "status.json"
        if status_path.exists():
            status = json.loads(status_path.read_text(encoding="utf-8"))
            if status.get("supported") is False:
                raise ReferenceLayoutError(
                    "Your uploaded resume's layout cannot be reproduced yet. "
                    + str(status.get("reason", ""))
                )
        return _load_assets(directory)
    except ReferenceLayoutError:
        raise
    except (OSError, ValueError, KeyError, TypeError, AttributeError, TTFError) as error:
        raise ReferenceLayoutError(
            "The uploaded resume's layout or fonts are missing or unreadable. Import the PDF again."
        ) from error


def _load_assets(directory):
    directory = Path(directory)
    metadata = json.loads((directory / "layout.json").read_text(encoding="utf-8"))
    if metadata.get("version") != 1:
        raise ReferenceLayoutError("Unsupported reference metadata version.")
    if set(metadata["fonts"]) != {"regular", "bold", "italic"}:
        raise ReferenceLayoutError("The reference is missing an original font face.")
    names = {}
    for style, asset in metadata["fonts"].items():
        filename = asset["file"]
        if Path(filename).name != filename:
            raise ReferenceLayoutError("Invalid reference font asset path.")
        data = (directory / filename).read_bytes()
        if _hash(data) != asset["sha256"]:
            raise ReferenceLayoutError(
                "Reference font asset changed; recapture the reference."
            )
        name = "Reference-" + _hash(data)[:12]
        font = _font(name, data)
        old_glyphs, old_widths = font.face.charToGlyph, font.face.charWidths
        if asset["unicode_to_code"] is not None:
            mapping = {
                int(char): code for char, code in asset["unicode_to_code"].items()
            }
            if any(code not in old_glyphs for code in mapping.values()):
                raise ReferenceLayoutError(
                    "Reference font encoding does not match embedded glyphs."
                )
            font.face.charToGlyph = {
                char: old_glyphs[code] for char, code in mapping.items()
            }
            font.face.charWidths = {
                char: old_widths[code] for char, code in mapping.items()
            }
        # ReportLab deduplicates dynamic fonts by internal face name. Distinct
        # captured subsets must not reuse an earlier/full font's Unicode map.
        font.face.name += ("-ref" + _hash(data)[:12]).encode("ascii")
        pdfmetrics.registerFont(font)
        names[style] = name
    return metadata["layout"], names


def _text(value):
    if isinstance(value, Mapping):
        if not confirmed(value):
            return ""
        value = value.get("text", value.get("value", ""))
    if isinstance(value, (list, tuple)):
        return ", ".join(filter(None, (_text(v) for v in value)))
    return smarten(str(value or ""))


class _Page:
    def __init__(self, layout, fonts):
        self.l, self.fonts = layout, fonts
        self.commands = []
        self.y = layout["first_header_top"]

    def width(self, text, style="regular", size=None):
        font = pdfmetrics.getFont(self.fonts[style])
        missing = {
            c for c in text if ord(SUPERSCRIPTS.get(c, c)) not in font.face.charToGlyph
        }
        if missing:
            raise ReferenceLayoutError(
                f"Embedded {style} font lacks characters {' '.join(sorted(missing))!r}; supply the same full font or revise wording."
            )
        return sum(
            pdfmetrics.stringWidth(
                SUPERSCRIPTS.get(c, c),
                self.fonts[style],
                (size or self.l["body_size"])
                * (SUPER_SCALE if c in SUPERSCRIPTS else 1),
            )
            for c in text
        )

    def draw(self, text, x, y, style="regular", size=None):
        if not text:
            return
        size = size or self.l["body_size"]
        width = self.width(text, style, size)
        if (
            x < self.l["left"] - 0.2
            or x + width > self.l["right"] + 0.2
            or y + size > self.l["bottom"]
        ):
            raise ReferenceOverflowError(
                "Resume exceeds the reference layout; shorten content without shrinking its font."
            )
        for part in re.split("([" + "".join(SUPERSCRIPTS) + "])", text):
            if not part:
                continue
            superscript = part in SUPERSCRIPTS
            actual_size = size * (SUPER_SCALE if superscript else 1)
            top = (
                y
                + self.l["ascent"] * (size - actual_size)
                - (SUPER_RISE if superscript else 0)
            )
            value = SUPERSCRIPTS.get(part, part)
            self.commands.append(("text", value, x, top, style, actual_size))
            x += pdfmetrics.stringWidth(value, self.fonts[style], actual_size)

    def row(self, left, date="", style="bold", trailing="", trailing_style="bold"):
        x = self.l["left"]
        date_x = self.l["right"] - self.width(date)
        if date and x + self.width(left, style) + self.width(trailing, trailing_style) > date_x - 10:
            raise ReferenceOverflowError(
                "Entry heading overlaps its date in the reference layout."
            )
        self.draw(left, x, self.y, style)
        if trailing:
            self.draw(trailing, x + self.width(left, style), self.y, trailing_style)
        self.draw(date, date_x, self.y)

    def wrapped(self, text, x=None, label=""):
        x = self.l["left"] if x is None else x
        prefix = self.width(label, "bold") if label else 0
        if label:
            self.draw(label, x, self.y, "bold")
        words = text.split()
        line = ""
        first = True
        for word in words:
            proposed = f"{line} {word}".strip()
            if line and self.width(proposed) > self.l["right"] - x - (
                prefix if first else 0
            ):
                self.draw(line, x + (prefix if first else 0), self.y)
                self.y += self.l["pitch"]
                line = word
                first = False
            else:
                line = proposed
        self.draw(line, x + (prefix if first else 0), self.y)


def _plan(profile, directory):
    resume = profile.resume if hasattr(profile, "resume") else profile
    l, fonts = _load(directory)
    p = _Page(l, fonts)
    name = _text(resume.get("name"))
    p.draw(
        name,
        (l["width"] - p.width(name, "bold", l["name_size"])) / 2
        if l.get("name_align", "center") == "center" else l["name_x"],
        l["name_top"],
        "bold",
        l["name_size"],
    )
    contact = resume.get("contact", {})
    if not confirmed(contact):
        contact = {}
    contact_text = l.get("contact_separator", " • ").join(
        filter(
            None,
            (
                _text(contact.get(key))
                for key in ("location", "phone", "email", "linkedin")
            ),
        )
    )
    contact_style, contact_size = l.get("contact_style", "regular"), l.get("contact_size", l["body_size"])
    contact_x = ((l["width"] - p.width(contact_text, contact_style, contact_size)) / 2
                 if l.get("contact_align", "center") == "center" else l["contact_x"])
    p.draw(contact_text, contact_x, l["contact_top"], contact_style, contact_size)
    first = True
    for section in sections(resume):
        entries = [
            e
            for e in resume.get(section["key"], [])
            if isinstance(e, Mapping) and confirmed(e)
        ]
        if not entries:
            continue
        if not first:
            p.y += l["section_gap"]
        first = False
        p.draw(_text(section["title"]), l["left"], p.y, "bold", l["section_size"])
        p.commands.append(("rule", p.y + l["rule_offset"]))
        kind = section.get("kind", "entries")
        p.y += l["labeled_header_gap"] if kind == "labeled" else l["header_gap"]
        for index, entry in enumerate(entries):
            if index:
                p.y += l["pitch"] if kind == "labeled" else l["entry_gap"]
            if kind == "labeled":
                p.wrapped(
                    _text(entry.get("items")), label=_text(entry.get("label")) + ": "
                )
                continue
            heading = section.get("heading", "org")
            subheading = section.get("subheading", "role")
            title = _text(entry.get(heading))
            date = _text(entry.get("dates", entry.get("date")))
            location = _text(entry.get("location")) if kind == "education" else ""
            p.row(title, date, trailing=" - " + location if location else "", trailing_style=l.get("education_location_style", "bold"))
            if kind == "titles":
                continue
            if kind == "education":
                for key, label in [
                    ("degree", ""),
                    ("gpa", "Cumulative GPA: "),
                    ("honors", "Honors: "),
                    ("coursework", "Relevant Coursework: "),
                    ("coursework_in_progress", "Coursework in Progress: "),
                ]:
                    text = _text(entry.get(key))
                    if text:
                        p.y += l["pitch"]
                        p.wrapped(
                            (label + text) if key == "gpa" else text,
                            label="" if key == "gpa" else label,
                        )
            else:
                subtitle = " - ".join(
                    filter(
                        None,
                        (_text(entry.get(subheading)), _text(entry.get("location"))),
                    )
                )
                if subtitle:
                    p.y += l["pitch"]
                    p.draw(subtitle, l["left"], p.y, "italic")
                for bullet in entry.get("bullets", []):
                    text = _text(bullet)
                    if not text:
                        continue
                    p.y += l["pitch"]
                    p.draw("•", l["bullet_x"], p.y, size=l.get("bullet_size", 10))
                    p.wrapped(text, l["bullet_text_x"])
    return p


def preflight_reference(profile, directory: Path | str) -> dict:
    """Validate all glyphs and geometry without creating a PDF."""
    plan = _plan(profile, directory)
    return dict(
        pages=1, bottom=plan.y + plan.l["body_size"], body_size=plan.l["body_size"]
    )


def render_reference(profile, out_path: Path | str, directory: Path | str) -> None:
    """Render only after preflight succeeds; existing output survives a failure."""
    plan = _plan(profile, directory)
    buffer = BytesIO()
    canvas = Canvas(buffer, pagesize=(plan.l["width"], plan.l["height"]))
    for command in plan.commands:
        if command[0] == "rule":
            y = plan.l["height"] - command[1]
            canvas.setLineWidth(plan.l["rule_width"])
            canvas.line(plan.l["rule_left"], y, plan.l["rule_right"], y)
        else:
            _, text, x, top, style, size = command
            canvas.setFont(plan.fonts[style], size)
            canvas.drawString(x, plan.l["height"] - top - plan.l["ascent"] * size, text)
    canvas.showPage()
    canvas.save()
    output = Path(out_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_bytes(buffer.getvalue())


def main(argv=None) -> int:
    """Capture assets in onboarding's staging directory; never invoke a provider."""
    import argparse
    import sys

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_pdf", type=Path)
    parser.add_argument("directory", type=Path)
    args = parser.parse_args(argv)
    try:
        try:
            capture_reference(args.source_pdf, args.directory)
            _load_assets(args.directory)
            outcome = {"supported": True}
        except (
            ReferenceLayoutError, PyPdfError, PDFException, TTFError,
            ValueError, KeyError, TypeError, IndexError, StopIteration,
        ) as error:
            # Retain the uploaded source in the staging directory. Incomplete
            # assets must never make a failed capture look like a usable layout.
            for filename in ("layout.json", "regular.ttf", "bold.ttf", "italic.ttf"):
                (args.directory / filename).unlink(missing_ok=True)
            reason = str(error) if isinstance(error, ReferenceLayoutError) else (
                "The PDF's text, fonts, or layout are not supported."
            )
            outcome = {"supported": False, "reason": reason}
        args.directory.mkdir(parents=True, exist_ok=True)
        (args.directory / "status.json").write_text(
            json.dumps(outcome) + "\n", encoding="utf-8", newline="\n"
        )
    except OSError:
        print("Could not read the uploaded PDF or save its layout.", file=sys.stderr)
        return 1
    print(json.dumps(outcome))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
