/**
 * Every filesystem location the dashboard resolves, in one module.
 *
 * The Install's boundary is its application data directory, not a Git checkout
 * (docs/adr/0002-checkout-is-the-tenant-boundary.md, as amended): the shipped product runs
 * for someone who has no clone, no `profiles/` beside the source, and no `build/` to read.
 * Every other module asks this one where something lives, so when the Python side lands its
 * own path seam the two can be reconciled here and nowhere else.
 *
 * Profiles are searched in the Install first, matching the pipeline; the fictional
 * example may still be read from a checkout. The view database is read only from
 * the Install unless an explicit path was named.
 *
 * Onboarding **writes** to exactly one place — `writableProfilesRoot()` — and never into the
 * checkout. That is the only write location this module hands out.
 */

import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const serverDirectory = dirname(fileURLToPath(import.meta.url));

/** `ui/` itself: the app bundle and the fixture live under it, wherever the checkout is. */
export const UI_ROOT = resolve(serverDirectory, "..");

/**
 * The repository one directory above `ui/`. Present when someone runs from a clone and
 * absent from a shipped Install, so it is a candidate for a location and never the answer.
 */
export const CHECKOUT_ROOT = resolve(UI_ROOT, "..");

/** Stand-in view, generated by `pnpm fixture`. Always badged on screen as a stand-in. */
export const FIXTURE_DATABASE_PATH = resolve(UI_ROOT, "fixtures/venator.fixture.db");

/** Built dashboard bundle; served by the API server when it exists. */
export const APP_BUNDLE_PATH = resolve(UI_ROOT, "dist");

/** The directory of Profiles, under whichever root holds it. */
export const PROFILES_DIRECTORY_NAME = "profiles";

/** The three files `src/venator/profile/loader.py` reads. A Profile directory holds them. */
export const PROFILE_FILES: readonly string[] = ["resume.yaml", "constraints.yaml", "targeting.yaml"];

/** Overrides the application data directory outright, for tests and for a portable Install. */
export const DATA_DIRECTORY_ENVIRONMENT = "VENATOR_HOME";

/** An explicit view database path; honoured ahead of every default, as it always has been. */
export const VIEW_DATABASE_ENVIRONMENT = "VENATOR_VIEW_DB";

/**
 * Asks for the sample view when this Install has no view of its own.
 *
 * The fixture holds nineteen Postings from real employers, and nothing about them is the
 * Owner's. So it is served on request and never by default: a developer with no pipeline
 * database wants the dashboard populated, and somebody who has just installed the app must
 * not be handed a stranger's job search however clearly it is badged. `pnpm dev`, `pnpm
 * smoke` and `pnpm snapshot` set this; nothing a shipped Install runs does.
 *
 * Any non-blank value means yes. There is no vocabulary of truthy words to get wrong, and a
 * variable somebody set to `0` meaning "off" is a person who has said the word `VENATOR_
 * SAMPLE_DATA` out loud — which is asking.
 */
export const SAMPLE_DATA_ENVIRONMENT = "VENATOR_SAMPLE_DATA";

/** The Python that runs the pipeline's own modules, when the caller has one in mind. */
export const PYTHON_ENVIRONMENT = "VENATOR_PYTHON";

/**
 * The Python the desktop bundle ships, named by the Tauri host that started this server.
 *
 * A desktop bundle carries CPython, the runtime wheel set and `src/venator` under
 * `resources/python/<triple>/`, and `ui/src-tauri/src/lib.rs` hands the interpreter's path over
 * when the file is there. Nothing else sets it: a development run has no bundled interpreter.
 *
 * It is a second name rather than the host writing into `VENATOR_PYTHON` because the two mean
 * different things. `VENATOR_PYTHON` is a person naming an interpreter deliberately, and it
 * still wins; this is a bundle stating what it shipped with.
 */
export const BUNDLED_PYTHON_ENVIRONMENT = "VENATOR_BUNDLED_PYTHON";

export type EnvironmentReader = (name: string) => string | undefined;

/**
 * Everything a location depends on, gathered so a test can state a machine rather than
 * being one. `systemContext()` is what the server uses.
 */
export type LocationContext = {
	readonly platform: NodeJS.Platform;
	readonly home: string;
	readonly workingDirectory: string;
	/**
	 * The repository this dashboard is running out of, or null when it is running from a
	 * shipped Install with no clone anywhere. It is a candidate for a location, never the
	 * answer — which is exactly why it is a value here rather than a constant in the code.
	 */
	readonly checkoutRoot: string | null;
	readonly environment: EnvironmentReader;
};

function readProcessEnvironment(name: string): string | undefined {
	return process.env[name];
}

export function systemContext(): LocationContext {
	return {
		platform: process.platform,
		home: process.env["HOME"] ?? process.env["USERPROFILE"] ?? "",
		workingDirectory: process.cwd(),
		checkoutRoot: CHECKOUT_ROOT,
		environment: readProcessEnvironment,
	};
}

/** A set environment variable that holds only whitespace is treated as unset, never as "". */
function configured(context: LocationContext, name: string): string | null {
	const value = context.environment(name);
	if (value === undefined) return null;
	const trimmed = value.trim();
	return trimmed === "" ? null : trimmed;
}

/**
 * Where this Install keeps its data.
 *
 * `$VENATOR_HOME` wins. Otherwise it is the platform's usual place:
 * `~/Library/Application Support/Venator` on macOS, `$XDG_DATA_HOME/venator` falling back to
 * `~/.local/share/venator` on Linux, `%APPDATA%\Venator` on Windows.
 */
export function applicationDataDirectory(context: LocationContext = systemContext()): string {
	const override = configured(context, DATA_DIRECTORY_ENVIRONMENT);
	if (override !== null) return resolve(context.workingDirectory, override);

	if (context.platform === "darwin") {
		return join(context.home, "Library", "Application Support", "Venator");
	}
	if (context.platform === "win32") {
		const appData = configured(context, "APPDATA");
		return appData === null ? join(context.home, "AppData", "Roaming", "Venator") : join(appData, "Venator");
	}
	const xdg = configured(context, "XDG_DATA_HOME");
	return xdg === null ? join(context.home, ".local", "share", "venator") : join(xdg, "venator");
}

function unique(paths: readonly string[]): readonly string[] {
	const seen = new Set<string>();
	const kept: string[] = [];
	for (const path of paths) {
		if (seen.has(path)) continue;
		seen.add(path);
		kept.push(path);
	}
	return kept;
}

/**
 * Where Profiles are looked for: the application data directory first, then the
 * working directory and checkout for the fictional example. Duplicates collapse.
 */
export function profileSearchRoots(context: LocationContext = systemContext()): readonly string[] {
	const checkout = context.checkoutRoot;
	return unique([
		join(applicationDataDirectory(context), PROFILES_DIRECTORY_NAME),
		resolve(context.workingDirectory, PROFILES_DIRECTORY_NAME),
		...(checkout === null ? [] : [join(checkout, PROFILES_DIRECTORY_NAME)]),
	]);
}

/**
 * The one directory onboarding may write a Profile into.
 *
 * It is always inside the application data directory. A checkout is somebody's working tree
 * — writing a person's own facts into it would put them under version control by accident.
 * Personal stores and Profiles belong outside Git.
 */
export function writableProfilesRoot(context: LocationContext = systemContext()): string {
	return join(applicationDataDirectory(context), PROFILES_DIRECTORY_NAME);
}

/**
 * The view databases to try, best first. `$VENATOR_VIEW_DB` names one outright; otherwise
 * only the application data directory is used (or the requested fixture when empty).
 */
export function viewDatabaseCandidates(context: LocationContext = systemContext()): readonly string[] {
	const explicit = configured(context, VIEW_DATABASE_ENVIRONMENT);
	if (explicit !== null) return [resolve(context.workingDirectory, explicit)];
	return [defaultViewDatabase(context)];
}

/**
 * Where `python -m venator.view.build` writes this Install's view, whether or not it has.
 *
 * Named separately from the candidate list because a dashboard with no view yet still has to
 * say where one will appear, and "nowhere" is not an answer anybody can act on.
 */
export function defaultViewDatabase(context: LocationContext = systemContext()): string {
	return join(applicationDataDirectory(context), "build", "venator.db");
}

/** True when `$VENATOR_VIEW_DB` named the database, so a caller can say the path was asked for. */
export function viewDatabaseWasConfigured(context: LocationContext = systemContext()): boolean {
	return configured(context, VIEW_DATABASE_ENVIRONMENT) !== null;
}

/** True when this run asked for the sample view. See `SAMPLE_DATA_ENVIRONMENT`. */
export function sampleDataRequested(context: LocationContext = systemContext()): boolean {
	return configured(context, SAMPLE_DATA_ENVIRONMENT) !== null;
}

/**
 * The interpreter this Install was *told* to use — by a person, then by the bundle — or null
 * when nothing named one and the answer will be found rather than given.
 *
 * Callers need the distinction to say something true when a launch fails: an interpreter that
 * was named and could not be started is a broken path or a broken runtime, and it is nothing
 * like an Install that simply has no Python in it.
 */
export function namedPythonInterpreter(context: LocationContext = systemContext()): string | null {
	for (const variable of [PYTHON_ENVIRONMENT, BUNDLED_PYTHON_ENVIRONMENT]) {
		const named = configured(context, variable);
		if (named !== null) return resolve(context.workingDirectory, named);
	}
	return null;
}

/**
 * The Python that can import `venator`.
 *
 * `$VENATOR_PYTHON` wins — someone naming an interpreter deliberately outranks everything.
 * Then the interpreter the desktop bundle shipped with, when the host named one: on the machine
 * the desktop bundle runs without a system Python, it is the interpreter it ships. It sits ahead of a checkout's `.venv` because what the app shipped with
 * is what the app should run, and the two can only ever meet when a packaged app is launched
 * from inside somebody's clone — where `$VENATOR_PYTHON` is how that person says otherwise.
 * Then a checkout's own `.venv`, because `uv sync` is what puts the package on its path, and a
 * bare interpreter is the last resort.
 *
 * Neither named interpreter is existence-checked here, and that is deliberate on both counts:
 * whoever named one wants the error rather than a substitute, and quietly falling back to a
 * system Python where a bundled one was expected would mean an Install running code it did not
 * ship. Nothing here checks that the module exists either — the caller runs the probe and
 * reports honestly when it does not.
 */
export function pythonInterpreter(context: LocationContext = systemContext()): string {
	const named = namedPythonInterpreter(context);
	if (named !== null) return named;
	const windows = context.platform === "win32";
	const checkout = context.checkoutRoot;
	const venv =
		checkout === null
			? null
			: windows
				? join(checkout, ".venv", "Scripts", "python.exe")
				: join(checkout, ".venv", "bin", "python");
	if (venv !== null && existsSync(venv)) return venv;
	return windows ? "python" : "python3";
}

/**
 * The working directory a pipeline subprocess runs in: the checkout when there is one, so a
 * `src/` layout resolves, then the data directory, then this process's own.
 *
 * The last leg is not decoration. A subprocess launched with a working directory that does
 * not exist fails at spawn with an error about the directory rather than about the pipeline,
 * which would be reported as "the runtime check is not installed" when the real answer is
 * that this Install has not written anything down yet.
 *
 * This stays the checkout when one exists for the Python `src/` layout, not for the
 * stores: `src/venator/paths.py` always selects the Install application data directory.
 * `-m` also puts this directory at the front of the child's `sys.path`, which is how
 * `ui/tests/runtime.test.ts` stages a stand-in package at all.
 *
 * The reason someone would want to neutralise it is real, and is fixed one layer down
 * instead. A coding agent started with no working directory of its own inherits its parent's,
 * so `claude` spawned from a run started here used to wake up in the checkout and read the
 * checkout's own `CLAUDE.md` into the prompt ahead of its own — measured at 9,896
 * extra input tokens per chunk, on the Owner's subscription, from a file that changes on most
 * commits and does not exist on an Install with no clone. `venator.llm.runtime.run_process`
 * now starts every runtime in a fresh empty directory it makes and removes for that one call,
 * so what this function returns no longer reaches the model. Fixing it there rather than here
 * is what makes it true of a run started from a terminal as well as one started from a button,
 * and of a lane added later that nobody remembered to think about.
 */
export function pipelineWorkingDirectory(context: LocationContext = systemContext()): string {
	const checkout = context.checkoutRoot;
	if (checkout !== null && existsSync(join(checkout, "src", "venator"))) return checkout;
	const data = applicationDataDirectory(context);
	return existsSync(data) ? data : context.workingDirectory;
}
