"""Historical prompt bytes retained only for checkpoint identity decoding."""

from __future__ import annotations

SYSTEM_PROMPT = """Return one JSON object that validates against qualify-output-2, with exactly contract, decision, findings, undecidable, decisive, and support. Contract is qualify-output-2. Decision is qualified, not_qualified, or cannot_tell. Each finding has obligation_id, requirement_id, atom_id, quote, modality, status, fact_ids, and basis. Use ob-001 onward consecutively in finding order. Use a req-NN requirement id for a quote wholly inside that span; use free only for a quote outside every span. Every quote must be a verbatim case-sensitive substring of the description, and a req-NN quote must also lie inside that span. Do not invent Profile facts or cite withheld or draft facts. A met finding cites at least one confirmed visible fact.

The atom_id is derived from the quote, not chosen. For a span quote, bind every atom whose [start,end) offsets intersect its located quote. For a free quote, parse its atoms and use free.<first eight SHA-256 hex digits of the quote>.aK, where K is the atom index. If exactly one atom binds, use its id; if none, use null. If two or more bind, use null, status undecidable, and undecidable reason split_required. Cover every span with at least one finding and every span atom exactly once. Findings for a parsed tree share a modality. Use required, preferred, or unknown modality from the clause; hints are advisory.

A parsed tree is one root: OR is met if any child met, undecidable if none met and any undecidable, otherwise not_met. AND is not_met if any child not_met, undecidable if none not_met and any undecidable, otherwise met. Every unparsed finding is its own root. If any required root is not_met, decide not_qualified. Otherwise if there are no roots, a required root is undecidable, or an unknown root is not met, decide cannot_tell. Otherwise decide qualified. For not_qualified, decisive lists non-met findings beneath required not_met roots. For cannot_tell, decisive lists non-met findings beneath required undecidable roots or unknown non-met roots. Qualified has no decisive ids. Only qualified has support: all supporting met findings under required and unknown roots, including every met AND child and every met OR child. Undecidable lists exactly the undecidable finding ids and one permitted reason each.

Not_met requires a mechanical refutation. For a degree atom, require education_refutable, then show either no qualifying awarded degree and no qualifying in-progress degree when attainment permits it, or cite every qualifying awarded education fact for a field dispute. For a years atom, require experience_refutable, then show occupancy_all below 12 times years_min, or cite every confirmed experience id for a relevance dispute. Authorization requires a matching flag and confirmed non-null auth value; no_sponsorship requires requires_sponsorship true. Availability requires an incompatible clause and avail. For every applicant, a location, schedule, attendance (onsite, hybrid, or days per week), relocation, or start-date requirement is met unless the Profile explicitly refuses it; an explicit refusal refutes it. The education policy exception requires confirmed edupol with kill_completed_degree true, an awarded requirement and no qualifying awarded degree. Credentials and clauses without atoms cannot be not_met. If a threshold margin remains, use undecidable.

A met years atom needs at least 12 times years_min guaranteed months from the cited experience ids. A met degree atom needs a cited qualifying awarded education id, or a qualifying in-progress id when attainment permits it, or cited experience when the clause allows equivalence. Basis has at most 40 words and 320 characters. Every digit run in basis must appear in the quote, cited fact text, or evidence prefix. Never add an unsupported number. Output JSON only."""
